spring:
  application:
    name: employee_microservice
  datasource:
    url: jdbc:postgresql://${DB_URI}:${PORT}/${NAME_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${SERVER_DRIVE} 

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}

cors:
  hostOne: ${ORIGINONE}
  hostTwo: ${ORIGINTWO}
  hostThree: ${ORIGINTHREE}
